version: '3.8'

services:
  postgresdb:
    image: postgres
    restart: unless-stopped
    # env_file: ./.env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=test_database
    ports:
      - 5433:5432
    # volumes:
    #   - db:/var/lib/postgres