version: '3.8'

services:
    postgresdb:
        image: postgres
        restart: unless-stopped
        env_file: ./.env
        environment:
            - POSTGRES_USER=$POSTGRESDB_USER
            - POSTGRES_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
            - POSTGRES_DB=$POSTGRESDB_DATABASE
        ports:
            - $POSTGRESDB_LOCAL_PORT:$POSTGRESDB_DOCKER_PORT
        volumes:
            - db:/var/lib/postgres
    app:
        depends_on:
            - postgresdb
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        env_file: ./.env
        ports:
            - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
            - 9229:9229
        environment:
            - NODE_ENV=development
            - POSTGRESDB_DB_HOST=$POSTGRESDB_DB_HOST
            - POSTGRESDB_USER=$POSTGRESDB_USER
            - POSTGRESDB_ROOT_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
            - POSTGRESDB_DATABASE=$POSTGRESDB_DATABASE
            - POSTGRESDB_DOCKER_PORT=$POSTGRESDB_DOCKER_PORT
        stdin_open: true
        tty: true

volumes:
    db:

    #command: ["node", "--inspect=0.0.0.0:9229", "server.js"]
